name: Continuous Deployment - Hemangini

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Navigate into Session4_Homework to find the requirements file
          cd Session4_Homework
        

      - name: Execute the main script
        # Update 'main.py' to the actual entry point of your pipeline script
        run: python Session4_Homework/main.py 

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Stage the directory where the model artifacts are saved
          git add models/
          git commit -m 'chore: generated new model' || echo "No changes to commit"
          git push origin main